Add workflow for Update Gradle Wrapper Action.
testcontainers/testcontainers-java pull request #3297
Opened 2020-10-02 07:56 UTC by cristiangreco

Hey there 👋, first of all thanks for your work on the TestContainers project!

I've got a suggested change: would you be willing to use [this GitHub Action](https://github.com/gradle-update/update-gradle-wrapper-action) to automatically keep Gradle Wrapper updated to latest release?

**What does "Update Gradle Wrapper Action" do?** It can be configured to run at scheduled intervals (e.g. daily or weekly) and will check whether the Wrapper script in the repo is up-to-date to the latest Gradle release: in case a new Gradle version is available, it will create a PR to update the Wrapper. And that's it!

**Why is that a good thing?** Well, first of all it alleviates the chore of manually updating the Wrapper, as you got a task that keeps track of new Gradle releases for you! More importantly, it boosts security around the Wrapper update and usage processes: this actions verifies that the `gradle-wrapper.jar` file has not been tampered with (uses checksum comparison), and it sets the `distributionSha256Sum` property so that the new Gradle binary itself will be verified locally upon download.

**Where can I find more about?** The [README](https://github.com/gradle-update/update-gradle-wrapper-action/blob/master/README.md) contains quite detailed information!

In this PR I propose adding a new workflow which runs the action every day at midnight (but feel free to adjust the frequency as you prefer). I've verified it works correctly in my fork of the repo, and you can [see here](https://github.com/gradle-update/testcontainers-java/pull/1) how a PR will look like.

The action is under active development, you can have a look at the [list of inputs](https://github.com/gradle-update/update-gradle-wrapper-action#action-inputs) currently supported. There's new features coming up soon and if you'd like to request any particular change just let me know!

I'd love to see the action used by TestContainers and I genuinely hope you can find this useful. Would love your feedback! ❤️

2020-10-02 09:03 UTC, rnorth commented
Hi @cristiangreco 

I think as a general principle we'd want to use Dependabot for all version bumping - but it doesn't cover Gradle version upgrades, so there's definitely a gap that this action addresses!

I think I'd be happy with a couple of tweaks:
* For third party GitHub Actions we'd like to always use a SHA rather than an unpinned version or a tag reference. It's more of a chore for us to upgrade actions, but less risk if something in the chain gets compromised.
* Would it be possible to customise the labels that get applied to the PR? For our purposes we'd like to have the `dependencies` label applied. Could the action be updated to accept a list of labels that overrides the default?
* We'd like to use the [Gradle-provided wrapper validation action](https://github.com/gradle/wrapper-validation-action) as well, even though there's some crossover in functionality with your library. Having validation being done by Gradle's own code would help satisfy our paranoia :)

Thanks
Richard

2020-10-02 10:41 UTC, cristiangreco commented
@rnorth thanks for your reply!

> For third party GitHub Actions we'd like to always use a SHA rather than an unpinned version or a tag reference. It's more of a chore for us to upgrade actions, but less risk if something in the chain gets compromised.

It makes sense to me if you want to stay on the safe side. You might not automatically benefit from new functionalities or fixes as v1 continues to get updated, but I totally understand that you want to have more control over a 3rd party repo that is not part of the Gradle org.

> Would it be possible to customise the labels that get applied to the PR? For our purposes we'd like to have the dependencies label applied. Could the action be updated to accept a list of labels that overrides the default?

Sure thing, will work on it! Would it be ok for your use case if the labels you specify are added to the one already set by the action?

> We'd like to use the Gradle-provided wrapper validation action as well, even though there's some crossover in functionality with your library. Having validation being done by Gradle's own code would help satisfy our paranoia :)

This is totally doable, you can add another step in the workflow that runs the WVA just after UGW.

Will update the PR with all the changes mentioned above 🙂

2020-10-02 10:55 UTC, rnorth commented
Thanks!

>  but I totally understand that you want to have more control over a 3rd party repo that is not part of the Gradle org.

It's not just not being part of the gradle org - actually we should use SHA pinning for the Gradle-provided action as well, because the same risk exists with that. We're just keen to make sure any action that isn't provided by GitHub themselves is pinned.

> Sure thing, will work on it! Would it be ok for your use case if the labels you specify are added to the one already set by the action?

Yep, absolutely fine! As long as we can add a specific label, we don't mind which other labels are there.

Thanks again

2020-10-03 17:20 UTC, cristiangreco commented
Hey @rnorth I've updated this PR with the requested changes:
- pinning to a sha (it's the one that corresponds to latest release, v1.0.9)
- setting an additional `dependencies` label
- additionally run the wrapper validation action at the end

Let me know if it looks ok to you 🙂

2020-10-03 20:32 UTC, bsideup approved these changes
👍

2020-10-11 06:22 UTC, rnorth approved these changes

2020-10-11 06:23 UTC, rnorth commented on .github/workflows/update-gradle-wrapper.yml
> +      - uses: gradle/wrapper-validation-action@v1
I'd just like to pin this as well!
```suggestion
      - uses: gradle/wrapper-validation-action@e2c57ac
```

2020-10-11 06:24 UTC, rnorth requested changes
Sorry, just spotted that the gradle action is not pinned!

2020-10-11 14:48 UTC, cristiangreco commented
> Sorry, just spotted that the gradle action is not pinned!

Sure, have committed your suggestion!

2020-10-11 16:53 UTC, rnorth approved these changes
Great, thanks!

2020-10-11 18:19 UTC, merged