Updated Vault docs, uplifted Vault image version
testcontainers/testcontainers-java pull request #3685
Opened 2021-01-13 15:03 UTC by RamazanYapparov

- changed code example in the docs to codeinclude
- removed `VaultClientTest` class and moved its test to `VaultContainerTest`
- uplifted Vault image version
- added `getVaultAddress` method for usage convenience

This PR is also related to #1158 issue

2021-03-10 12:21 UTC, vcvitaly commented
I'm not a vault user but looks good at a first glance.

2021-03-20 09:37 UTC, rnorth commented on modules/vault/src/test/java/org/testcontainers/vault/VaultContainerTest.java
> +    // readWithHttpApi {
This comment isn't really necessary - we could have the `codeinclude` tag in the docs just say: `inside_block:readFirstSecretPathOverHttpApi`.

2021-03-20 09:39 UTC, rnorth commented on modules/vault/src/test/java/org/testcontainers/vault/VaultContainerTest.java
>          given().
I know the `given/when/then` style test was here originally, but would mind refactoring these  test methods to use plain style (e.g. `readFirstSecretPathOverClientLibrary`)?

It feels really strange to see `given/when/then` appearing in the documentation: 
<img width="836" alt="image" src="https://user-images.githubusercontent.com/132175/111865646-270d9780-8960-11eb-8bf6-2d25a59b0947.png">

2021-03-20 09:41 UTC, rnorth requested changes
Thanks for the contribution - a couple of minor changes but I'm grateful that you're helping to improve the docs.

2022-08-24 13:24 UTC, eddumelendez requested changes
I like the docs improvements and the new `getVaultAddress`. @RamazanYapparov is there a chance to rebase the branch, resolve the conflicts (for example, we already use assertj) and make the changes requested?

2022-08-24 13:24 UTC, eddumelendez commented on modules/vault/src/main/java/org/testcontainers/vault/VaultContainer.java
> +    private static final String DEFAULT_TAG = "1.6.1";
it is not needed

2022-11-07 16:46 UTC, merged