Remove jcenter from list of repositories
testcontainers/testcontainers-java pull request #3755
Opened 2021-02-04 19:28 UTC by gastaldi

See https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ for more details

2021-02-05 09:56 UTC, slonopotamus commented
Note that this is not the only dependency on jcenter/bintray in testcontainers.

As far as I understand, testcontainers currently publishes its releases via bintray: https://github.com/testcontainers/testcontainers-java/blob/master/gradle/bintray.gradle

2021-02-06 15:25 UTC, bsideup commented
@gastaldi could you please remove it from everywhere, not only the top level file? There are a few entries (e.g. examples)

2021-02-08 15:11 UTC, gastaldi commented
@bsideup My Gradle-fu is a bit limited, but I think I removed every reference from the repository, except for the `RELEASING.md`, which says that Bintray syncs with Central and I have no idea how to do that in Gradle :)

2021-06-24 09:39 UTC, rnorth requested changes

2021-06-24 09:39 UTC, rnorth commented on build.gradle
> -    id "com.jfrog.bintray" version "1.8.4" apply false
It's not quite as easy as this; we need to replace our bintray publication with something else, and I'm afraid that this is a task that core maintainers need to do.

Removal of `jcenter()` from `repositories` blocks is still valuable, though!

2022-05-17 23:27 UTC, bsideup commented
Seems to be superseeded by #4931, sorry! Thanks for your time working on this PR tho, much appreciated!

2022-05-17 23:27 UTC, closed without merging