Modernize Oracle Container Logic
testcontainers/testcontainers-java pull request #4402
Opened 2021-09-01 18:48 UTC by KyleAure

Now that we are using a standard Oracle image.  
The Oracle Container logic needs to change to support the oracle database config options on `gvenzl/oracle-xe`

The following options are now configurable and no longer static:
- system / sys password
- Application username and password
- Pluggable database name

The following options are still static but need to be accounted for:
- SID is static and will always be `XE`

Additional method paths:
- Connect using SID, or service name (pluggable database name)

Finally: 
- Add a waitStrategy that aligns with other JDBC containers.

2021-09-11 19:34 UTC, sualeh commented
Please merge this change - this is the only way to use Oracle 11 with Testcontainers, using "gvenzl/oracle-xe".

2021-09-11 19:59 UTC, KyleAure commented
@rnorth let me know if you think this would be a good first PR towards getting the Oracle container on par with the others.

2021-09-11 20:23 UTC, sualeh commented
@KyleAure - in a later PR, we could add "withSID" and "withServiceName". For now, your code works - I tried it out with Testcontainers 1.16.0.

2021-09-13 19:51 UTC, KyleAure commented
@sualeh I am not sure we need `withSID` and `withServiceName` methods.  Since this container architecture assumes you are using an Oracle XE image then the SID is static and will always be `XE`.  I think it is reasonable that if a user of testcontainers is using a non-standard or non-XE oracle image then they will either extend this class, or create their own container class. 

As for `withServiceName` the same logic applies.  The Oracle XE image uses a standard service name, also `XE`.  

Oracle has engineered these images to really only allow customization of pluggable databases.  Therefore, `withDatabaseName` and `getDatabaseName` seem to be the standard. 

This does contradict some of the suggestions I had on this PR: #4382 
But I think aligning this container with what is actually configurable out of the box for this image makes the most sense.

2021-09-22 16:06 UTC, kiview requested changes
Hey @KyleAure, 
thanks for reiterating on this PR. With regards to the changes potentially coming through #4382, I would see the scope of this PR as brining all the capabilities of the `gvenzl` image to the class.

This means:
* Support for using another pluggable database
* Leveraging the faster `LogMessageWaitStrategy` for known log message

In addition, it would be great if we have tests for all main permutations of the container:
  - no databaseName set, user/pw default
  - databaseName set, user/pw default
  - databaseName set, user/pw set
  - no databaseName set, user/pw set

While you are right that the image does not support customizing serviceName or SID, custom user images might. So we can think about adding setters in a future PR (although we have no easy way to test them).

Since we currently assume strict compatibility with the `gvenzl` image, please add the following assertion, similarly to how it is done for e.g. the `PostgreSQLContainer`:
```
dockerImageName.assertCompatibleWith(DEFAULT_IMAGE_NAME);
```


@sualeh Which aspect of this PR do you require for making the module working with Oracle 11 and the `gvenzl` image?

2021-09-22 18:31 UTC, sualeh commented
@KyleAure - [these lines](https://github.com/testcontainers/testcontainers-java/pull/4402/files#diff-905e446c5771ff2c88cbbadfc948f520073090b6d3234ef4f914364f74a0ec0fR106-R108) take care of Oracle 11 and above.

2021-09-22 21:58 UTC, KyleAure commented
@kiview I have updated my PR based on the feedback you provided. Thank you.

2021-09-23 08:14 UTC, kiview commented
@KyleAure Thanks, I will have another look.

@sualeh I don't understand this. Even without this change, the current test uses `gvenzl/oracle-xe:18.4.0-slim` and it works. But you are right that `gvenzl/oracle-xe:11` does not work. So while versions above 11 (version 18 to be precise) are support, version 11 is currently not. Is that what you meant?

2021-09-23 09:37 UTC, kiview commented on modules/oracle-xe/src/main/java/org/testcontainers/containers/OracleContainer.java
> +        //Only set ORACLE_DATABASE if different than the default
```suggestion
        // Only set ORACLE_DATABASE if different than the default.
        // This will create a new pluggable database
```

2021-09-23 09:39 UTC, kiview commented on modules/oracle-xe/src/main/java/org/testcontainers/containers/OracleContainer.java
> +    public boolean isUsingSid() {
Do you think this public method is necessary for users?

2021-09-23 09:43 UTC, kiview requested changes
I think the PR looks great, thanks a lot for the quick rework!
Just having small minor comments and questions, after that, it's good to go from my side.

@rnorth can you have an additional look?

2021-09-24 09:10 UTC, rnorth commented on modules/oracle-xe/src/main/java/org/testcontainers/containers/OracleContainer.java
> +        if (ORACLE_DEFAULT_DBS.contains(databaseName.toLowerCase())) {
We could simpify this to `DEFAULT_DATABASE_NAME.equals(databaseName.toLowerCase())`, couldn't we? As-is looks like it's future-proofing, but for now `ORACLE_DEFAULT_DBS` is just a constant list with one value, so it doesn't feel like we need to do this just yet.

2021-09-24 16:51 UTC, KyleAure commented
@rnorth @kiview Updated the PR with your suggested changes. Thanks for the feedback 👍🏼

2021-09-24 17:32 UTC, sualeh commented
> @sualeh I don't understand this. Even without this change, the current test uses `gvenzl/oracle-xe:18.4.0-slim` and it works. But you are right that `gvenzl/oracle-xe:11` does not work. So while versions above 11 (version 18 to be precise) are supported, version 11 is currently not. Is that what you meant?

@kiview - if you use the Oracle Testcontainer with a different tag (11) with SID, it works. 

```java
dbContainer =
      new OracleContainer(DockerImageName.parse("gvenzl/oracle-xe").withTag("11")).usingSid();
``

2021-09-24 18:47 UTC, KyleAure commented
@sualeh Is correct that the `11` docker image only supports connections  using SID.  Perhaps we could include startup logic to ensures that if the docker image is for `11` that SID must be enabled.

2021-09-25 17:46 UTC, sualeh commented
> @sualeh Is correct that the `11` docker image only supports connections using SID. Perhaps we could include startup logic to ensures that if the docker image is for `11` that SID must be enabled.

@KyleAure - the philosophy of Testcontainers seems to be (as far as I can tell) to create JDBC containers in such as way that the image can switched out. For this reason, I would not build in startup logic to check if the Docker image is "11". 

On the other hand, @rnorth @kiview -  what do you think about creating a sort of "base" JDBC container for each type of database system, where the image can be switched out, and then a concrete JDBC container as well, where the image cannot be switched out?  The concrete JDBC container can be used with all the default settings by a casual Testcontainers user, lowering the barrier to entry. Taking Oracle as an example, there would be 3 JDBC containers - a "base" one looking like what we have now, an Oracle 11 one with gvenzl/oracle-xe and SID baked in, and an Oracle 18 one with gvenzl/oracle-xe baked in too, with a service name. Thoughts?

2021-09-27 08:37 UTC, kiview commented
Testcontainers container implementation generally have a lot of assumptions about the underlying image and sometimes integrate against some slightly weak indicators or aspects, that might change in future versions or in custom images (the log message that is used now for waiting is one example for this). Therefore, we added the `dockerImageName.assertCompatibleWith(DEFAULT_IMAGE_NAME);` pattern, to be explicit to users if other images are used.

Let's try to not do too much auto-config for aspects users can easily specify if they know about the aspects of the underlying image (e.g. using SID in this case). This only created more weak integration points that might break and need to be maintained.

PR LGTM, thanks a @KyleAure and also thanks @sualeh for your feedback and explanations.

2021-09-27 08:38 UTC, kiview approved these changes

2021-09-27 08:44 UTC, rnorth approved these changes

2021-09-27 08:56 UTC, merged