Switch default image to ghcr.io and update default tag to 2.3.0
testcontainers/testcontainers-java pull request #5173
Opened 2022-03-14 09:06 UTC by gmunozfe

Toxiproxy is no longer updating their images in dockerhub but in ghcr. 

Updated DEFAULT_IMAGE_NAME to "[ghcr.io/shopify/toxiproxy](http://ghcr.io/shopify/toxiproxy)" and DEFAULT_TAG to "2.3.0". Notice that "toxiproxy-java" library 2.1.5 (the one included in testcontainers module) is compatible with 2.3.0.

2022-03-18 22:15 UTC, Aloren commented
@gmunozfe 2.4.0 is the latest version. Maybe makes sense to use it instead of 2.3.0?

2022-03-18 23:15 UTC, gmunozfe commented
@Aloren sure, updated with the last one, thanks for pointing out

2022-04-18 14:02 UTC, gmunozfe commented
hi, any update on this?

2022-06-16 23:08 UTC, eddumelendez requested changes
thanks for your contribution @gmunozfe ! I have added a suggestion, after that I would be glad to merge it.

2022-06-16 23:08 UTC, eddumelendez commented on modules/toxiproxy/src/main/java/org/testcontainers/containers/ToxiproxyContainer.java
> +    private static final DockerImageName DEFAULT_IMAGE_NAME = DockerImageName.parse("ghcr.io/shopify/toxiproxy");
we need to keep backward compatibility, in this case I would suggest to add a new image name

```java
private static final DockerImageName GHCR_IMAGE_NAME = DockerImageName.parse("ghcr.io/shopify/toxiproxy");
```

and add it [here](https://github.com/testcontainers/testcontainers-java/blob/de1324ed2800eff4da326d0c23d281399d006bc0/modules/toxiproxy/src/main/java/org/testcontainers/containers/ToxiproxyContainer.java#L56)

```java
dockerImageName.assertCompatibleWith(DEFAULT_IMAGE_NAME, GHCR_IMAGE_NAME);
```

2022-06-28 04:57 UTC, eddumelendez approved these changes

2022-06-28 04:58 UTC, merged