Fix incorrect path for RABBITMQ_CONFIG_FILE
testcontainers/testcontainers-java pull request #5184
Opened 2022-03-27 01:06 UTC by mdedetrich

Fixes a bug where the `RABBITMQ_CONFIG_FILE` was pointing to an incorrect path (i.e. `"/etc/rabbitmq/rabbitmq-custom"` rather than `"/etc/rabbitmq/rabbitmq-custom.conf"` ) which meant that the `withEnv` didn't end up doing anything since it was pointing to a path rather than a file. The tests didn't pick up this bug because they were just testing the existence of `/etc/rabbitmq/rabbitmq-custom.conf` and not the contents. Due to this the tests were updated to make sure the actual contents of `/etc/rabbitmq/rabbitmq-custom.conf` is the same as the `MountableFile` that gets passed in.

The other related tests have also been updated to make sure that they work as expected.

2022-03-27 01:11 UTC, mdedetrich commented
Doc generation appears to be failing but it appears to be unrelated since its some issue with Python on deploying docs, i.e.

```
3:07:36 AM: Traceback (most recent call last):
3:07:36 AM:   File "/opt/buildhome/python3.7/bin/mkdocs", line 8, in <module>
3:07:36 AM:     sys.exit(cli())
3:07:36 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
3:07:36 AM:     return self.main(*args, **kwargs)
3:07:36 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 1053, in main
3:07:36 AM:     rv = self.invoke(ctx)
3:07:36 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
3:07:36 AM:     return _process_result(sub_ctx.command.invoke(sub_ctx))
3:07:36 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
3:07:36 AM:     return ctx.invoke(self.callback, **ctx.params)
3:07:36 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 754, in invoke
3:07:36 AM:     return __callback(*args, **kwargs)
3:07:36 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/__main__.py", line 187, in build_command
3:07:36 AM:     build.build(config.load_config(**kwargs), dirty=not clean)
3:07:36 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/config/base.py", line 216, in load_config
3:07:36 AM:     from mkdocs.config.defaults import get_schema
3:07:36 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/config/defaults.py", line 1, in <module>
3:07:36 AM:     from mkdocs.config import config_options
3:07:36 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/config/config_options.py", line 8, in <module>
3:07:36 AM:     from mkdocs import utils, theme, plugins
3:07:36 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/theme.py", line 6, in <module>
3:07:36 AM:     from mkdocs.utils import filters
3:07:36 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/utils/filters.py", line 13, in <module>
3:07:36 AM:     @jinja2.contextfilter
3:07:36 AM: AttributeError: module 'jinja2' has no attribute 'contextfilter'
```

2022-03-28 14:47 UTC, kiview requested changes
Great catch @mdedetrich and thanks for providing this PR!
The docs error is indeed unrelated to this PR, we will fix this in https://github.com/testcontainers/testcontainers-java/pull/5186.

The only thing I would like us to reconsider is if we can somehow test that the configured and copied config file comes into effect, rather than testing for the implementation detail of it being present in a certain location of the container. Do you have an idea for using a specific config somewhere, that would allow for this?

2022-04-07 11:48 UTC, kiview commented
I changed the tests to check if the effect of changing the log level is applied through them.

2022-04-07 13:10 UTC, mdedetrich commented
Sorry for taking so long, I was a bit busy. @kiview are more things required?

2022-04-07 13:36 UTC, kiview approved these changes
Np, I just adopted the tests accordingly, thanks for your contribution 👍

2022-04-07 16:03 UTC, merged