Ensure that directory permissions are properly set on MySQL and MariaDB
testcontainers/testcontainers-java pull request #5401
Opened 2022-05-31 12:16 UTC by driverpt

Fixes #914 #4952

2022-06-08 01:41 UTC, eddumelendez requested changes
thanks for your contribution @driverpt ! Can you please run `./gradlew spotlessApply`? and please add tests for MariaDB too.

2022-06-08 01:41 UTC, eddumelendez commented on modules/mariadb/src/main/java/org/testcontainers/containers/MariaDBContainer.java
> +            Transferable.DEFAULT_FILE_MODE
I think this should be `Transferable.DEFAULT_DIR_MODE`, right?

2023-01-27 14:58 UTC, famod commented
@driverpt are you able to finish this (soon)? If not I'll try and come up with a superseding PR.

2023-01-27 15:03 UTC, driverpt commented
Hi. Please proceed. I can only pick this up next week

2023-01-30 15:56 UTC, famod commented
Hi @driverpt! I haven't been able to work on this so far. Please leave a message when you have picked it up again so that we don't work on it in parallel. Thanks!

2023-01-30 20:19 UTC, driverpt commented
Hey @famod , please feel free to pick this up. I'm a bit swamped with work atm.

2023-02-01 22:59 UTC, famod commented
FYI, I have started working on this. The tests need some work though.

2023-02-01 23:15 UTC, driverpt commented
That was where I had a hard time. To reproduce you need a Linux Operating system with 020 of default umask. I've tried doing that using docker-in-docker, but it's tricky

2023-02-01 23:18 UTC, famod commented
Actually, I don't think it's that complicated (unless I'm missing something):
`startFailsWithWrongPermissions` (which sets the file to owner-readable only) fails before the change and must not fail after it, that's all!
The second test method is obsolete/broken IMO.

2023-02-13 22:03 UTC, famod commented
Superseded by #6625, finally 😅

2023-02-14 03:17 UTC, eddumelendez commented
Close it favor of #6625

2023-02-14 03:18 UTC, closed without merging