The hardcoded 30 minutes timeout should be configurable
testcontainers/testcontainers-java pull request #5588
Opened 2022-07-08 14:52 UTC by henri-tremblay

2022-07-25 02:41 UTC, eddumelendez requested changes
Thanks for the pr @henri-tremblay ! I have left some comments

2022-07-25 02:41 UTC, eddumelendez commented on core/src/main/java/org/testcontainers/containers/DockerComposeContainer.java
> +    private Duration maximumTimeout = Duration.ofMinutes(30);
let's rename it to `startupTimeout`

2022-07-25 02:41 UTC, eddumelendez commented on core/src/main/java/org/testcontainers/containers/DockerComposeContainer.java
> +    public SELF withMaximumTimeout(Duration maximumTimeout) {
let's rename it to `withStartupTimeout`

2022-07-25 09:02 UTC, henri-tremblay commented on core/src/main/java/org/testcontainers/containers/DockerComposeContainer.java
> +    public SELF withMaximumTimeout(Duration maximumTimeout) {
Done

2022-07-25 09:02 UTC, henri-tremblay commented on core/src/main/java/org/testcontainers/containers/DockerComposeContainer.java
> +    private Duration maximumTimeout = Duration.ofMinutes(30);
Done

2022-07-28 15:46 UTC, eddumelendez approved these changes

2022-07-29 10:33 UTC, merged

2022-07-29 10:33 UTC, kiview commented
Thanks for your contribution @henri-tremblay 🙂

2022-07-30 00:23 UTC, henri-tremblay commented
You are welcome. Thanks for merging it.