Make Localstack services optional.
testcontainers/testcontainers-java pull request #6430
Opened 2023-01-21 08:29 UTC by maciejwalkowiak

Fixes #6428

2023-02-06 17:27 UTC, eddumelendez requested changes
Thanks for your contribution, @maciejwalkowiak ! I have added some comments.

2023-02-06 17:27 UTC, eddumelendez commented on modules/localstack/src/main/java/org/testcontainers/containers/localstack/LocalStackContainer.java
> +    private final boolean servicesListRequired;
```suggestion
    private final boolean servicesEnvVarRequired;
```

2023-02-06 17:27 UTC, eddumelendez commented on modules/localstack/src/main/java/org/testcontainers/containers/localstack/LocalStackContainer.java
> +    private static boolean isServicesListRequired(String version) {
```suggestion
    private static boolean isServicesEnvVarRequired(String version) {
```

2023-02-06 17:27 UTC, eddumelendez commented on modules/localstack/src/main/java/org/testcontainers/containers/localstack/LocalStackContainer.java
> +        this.servicesListRequired = isServicesListRequired(dockerImageName.getVersionPart());
```suggestion
        this.servicesEnvVarRequired = isServicesEnvVarRequired(dockerImageName.getVersionPart());
```

2023-02-06 17:27 UTC, eddumelendez commented on modules/localstack/src/main/java/org/testcontainers/containers/localstack/LocalStackContainer.java
> +        if (servicesListRequired) {
```suggestion
        if (this.servicesEnvVarRequired) {
```

2023-02-06 17:27 UTC, eddumelendez commented on modules/localstack/src/main/java/org/testcontainers/containers/localstack/LocalStackContainer.java
> +        }
> Scripts that depend on the output of /health being running will require setting setting EAGER_SERVICE_LOADING=1, which will start all services eagerly. This works together with the SERVICES variable to create the behavior from localstack <= 0.13.0.

Following the note from the release notes and do not break things


```suggestion
            if (this.servicesEnvVarRequired) {
                withEnv("EAGER_SERVICE_LOADING", "1");
            }
        }
```

2023-02-06 17:27 UTC, eddumelendez commented on modules/localstack/src/test/java/org/testcontainers/containers/localstack/LocalstackContainerTest.java
> +        public void startsServicesLazily() {
```suggestion
        public void s3ServiceStartLazily() {
```

2023-02-06 17:27 UTC, eddumelendez commented on modules/localstack/src/test/java/org/testcontainers/containers/localstack/LocalstackContainerTest.java
> +
It's already covered https://github.com/testcontainers/testcontainers-java/blob/main/modules/localstack/src/test/java/org/testcontainers/containers/localstack/LegacyModeTest.java#L48

```suggestion
```

2023-02-11 05:20 UTC, merged

2023-02-11 05:21 UTC, eddumelendez commented
Thanks for your contribution, @maciejwalkowiak ! I've applied the suggestions.

2023-02-11 05:36 UTC, maciejwalkowiak commented
Thanks @eddumelendez!