Add real `on_failure` page
testcontainers/testcontainers-java pull request #6784
Opened 2023-03-16 13:50 UTC by kiview

When Testcontainers fails to automatically discover a supported container runtime environments, it will log a human readable error message with a link, pointing to https://www.testcontainers.org/supported_docker_environment/. In order to give new users with less Docker experience more suitable hints on how to fix their issue, we intend to explore ways to make the documentation more streamlined.

2023-04-10 16:16 UTC, mtremsal requested changes
Some suggestions to clean-up the language a bit.

2023-04-10 16:16 UTC, mtremsal commented on docs/_redirects
> +/on_failure.html                        /on_failure
Let's have a more descriptive url. e.g. `error_missing_container_runtime_environment.html`

2023-04-10 16:16 UTC, mtremsal commented on docs/on_failure.md
> +or you found page while browsing the documentation in search of information on dealing with errors regarding Testcontainers' environment discovery mechanism.
or you found _this_ page while searching for information to deal with errors regarding the environment discovery mechanism of Testcontainers.

2023-04-10 16:16 UTC, mtremsal commented on docs/on_failure.md
> +Testcontainers requires a supported container runtime environment to be present in order to function.
Testcontainers requires a supported container runtime environment to be present in order to execute containers.

2023-04-10 16:16 UTC, mtremsal commented on docs/on_failure.md
> +Here is a list of supported container runtime environments, that can get you up to speed quickly:
Here is a list of supported container runtime environments:

2023-04-10 16:16 UTC, mtremsal commented on docs/on_failure.md
> +For more extensive information on supported container runtime environments, and how to configure container runtime environments that are not supported by default,
For more extensive information on supported container runtime environments, as well as known limitations of alternative container runtime environments, please refer to...

2023-04-10 16:54 UTC, mtremsal approved these changes
LGTM -- thanks for the changes 👍

2023-04-11 11:25 UTC, kiview commented
Thanks for the review @mtremsal and thanks for applying the changes @shelajev 👍

2023-04-11 11:25 UTC, merged