Add CrateDB testcontainers
testcontainers/testcontainers-java pull request #6790
Opened 2023-03-20 14:21 UTC by matriv

Addresses: #6789

2023-03-29 14:26 UTC, eddumelendez requested changes
Thanks for your contribution, @matriv ! I have left some comments and we suggest to remove the legacy driver given it is a new module.

Also, please do not use force push.

2023-03-29 14:26 UTC, eddumelendez commented on modules/jdbc/src/main/java/org/testcontainers/jdbc/ConnectionUrl.java
> +            "(?<databaseType>[a-z0-9_]+)" +
rollback this change

2023-03-29 14:26 UTC, eddumelendez commented on modules/jdbc/src/test/java/org/testcontainers/jdbc/ConnectionUrlTest.java
> +        String urlString = "jdbc:tc:my_db:5.7.34://somehostname:3306/databasename?a=b&c=d";
rollback this change

2023-03-29 14:26 UTC, eddumelendez commented on modules/jdbc/src/test/java/org/testcontainers/jdbc/ConnectionUrlTest.java
> +        assertThat(url.getDatabaseType()).as("Database Type value is as expected").isEqualTo("my_db");
rollback this change

2023-03-29 14:50 UTC, matriv commented on modules/cratedb/src/test/java/org/testcontainers/CrateDBTestImages.java
> +public interface CrateDBTestImages {
What do you mean: avoid doing this?
Should I use a constant in the test classes that need it instead?

2023-03-29 14:59 UTC, matriv commented
Thx a lot for reviewing the PR @eddumelendez !
>  we suggest to remove the legacy driver given it is a new module.

There are certain places that still require the legacy driver, because if vanilla Postgres is used,
they assume things about the internal structures/tables where CrateDB is not 100% combatible, see [this example](https://github.com/apache/flink-connector-jdbc/pull/29/files#diff-2de81db8fb3556629101d31f0a22ffcf7f4e446f7f9cec24b24f56836a445d81R68)

Although, there is a workaround for such cases, so if you prefer not to include the legacy version, I'd be happy to remove it.

> Also, please do not use force push.

Apologies, I didn't change anything in my PR, just rebased with `main`.  I won't force push again of course, no that the PR is in review.

2023-03-30 08:41 UTC, eddumelendez commented
@matriv thanks for the quick update! Please, let's remove the legacy version

2023-03-30 08:43 UTC, matriv commented
> @matriv thanks for the quick update! Please, let's remove the legacy version

It's reasonable, thx! please also check: https://github.com/testcontainers/testcontainers-java/pull/6790#discussion_r1152070909

2023-03-30 08:48 UTC, matriv commented on modules/cratedb/src/test/java/org/testcontainers/CrateDBTestImages.java
> +public interface CrateDBTestImages {
no worries, thx!

2023-03-30 08:49 UTC, matriv commented
I believe I've had addressed your comments so far, removed the legacy version, please have another look, many thx!

2023-03-31 23:21 UTC, eddumelendez approved these changes

2023-03-31 23:22 UTC, merged

2023-03-31 23:22 UTC, eddumelendez commented
Thanks for your contribution, @matriv ! This is now merged in `main` branch and it will be part of the next release.

2023-04-01 05:36 UTC, matriv commented
Thx a lot for reviewing and merging!