Add Kotest to Test Framework Integrations
testcontainers/testcontainers-java pull request #6930
Opened 2023-04-19 22:29 UTC by LeoColman

This commit adds documentation on how TestContainers can be integrated with the Kotest framework.

From the very old #2533 it was decided that a reference to Kotest would be great in the docs. This commit adds it.

2023-04-19 22:38 UTC, eddumelendez requested changes
Thanks for the contribution! I've left some comments

2023-04-19 22:38 UTC, eddumelendez commented on docs/test_framework_integration/kotest.md
> +The source code is maintained at [Kotest Extensions TestContainers](https://github.com/kotest/kotest-extensions-testcontainers)
```suggestion
The source code is maintained at [Kotest Extensions Testcontainers](https://github.com/kotest/kotest-extensions-testcontainers)
```

2023-04-19 22:38 UTC, eddumelendez commented on docs/test_framework_integration/kotest.md
> +The full and updated documentation for Kotest integration with TestContainers can be found at [kotest.io](https://kotest.io/docs/extensions/test_containers.html)
```suggestion
The full and updated documentation for Kotest integration with Testcontainers can be found at [kotest.io](https://kotest.io/docs/extensions/test_containers.html)
```

2023-04-20 22:56 UTC, LeoColman commented
Done :)

2023-04-20 23:45 UTC, eddumelendez commented
Hi @LeoColman, thinking more about this... I think we should not duplicate the existing documentation in kotest but we should point to it. what do you think about renaming the file to integration and then add Kotest with a link to https://kotest.io/docs/extensions/test_containers.html

The content can says something like `The following open source projects use Testcontainers`

2023-04-21 00:04 UTC, LeoColman commented
I agree!

I even tried to make it smaller to avoid maintenance issues.

How could I apply your suggestion?

Apr 20, 2023 19:46:14 Eddú Meléndez Gonzales ***@***.***>:

> 
> Hi @LeoColman[https://github.com/LeoColman], thinking more about this... I think we should not duplicate the existing documentation in kotest but we should point to it. what do you think about renaming the file to integration and then add Kotest with a link to https://kotest.io/docs/extensions/test_containers.html
> 
> The content can says something like *The following open source projects use Testcontainers*
> 
> —
> Reply to this email directly, view it on GitHub[https://github.com/testcontainers/testcontainers-java/pull/6930#issuecomment-1517066159], or unsubscribe[https://github.com/notifications/unsubscribe-auth/AAMBCI7FIZCNKMDDT3MKGLLXCHDEDANCNFSM6AAAAAAXEV2VXY].
> You are receiving this because you were mentioned.[Tracking image][https://github.com/notifications/beacon/AAMBCI6NH45AMXKBGEDNKN3XCHDEDA5CNFSM6AAAAAAXEV2VX2WGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTS2NSL26.gif]
>

2023-04-21 00:22 UTC, eddumelendez commented
Just update this PR :)

2023-04-21 14:44 UTC, LeoColman commented
Alright, I renamed it to `external` and replaced the documentation with links to the module itself.


Also took the opportunity to add another integration from #3298 to the same page. <-- @jlink @gtrefs

2023-04-21 14:45 UTC, LeoColman commented
I thought of adding a `last updated` or `last maintained` to each of them, to prevent accidentally using a very old framework. Let me know what you think @eddumelendez

2023-04-21 18:24 UTC, eddumelendez commented on docs/test_framework_integration/external.md
> +
```suggestion
```

2023-04-21 18:24 UTC, eddumelendez approved these changes

2023-04-21 18:26 UTC, merged

2023-04-21 18:26 UTC, eddumelendez commented
Thanks for your contribution, @LeoColman ! This will be available soon!