#6921 JUnit 4 to JUnit 5 Migration of all the examples
testcontainers/testcontainers-java pull request #6950
Opened 2023-05-01 08:16 UTC by nagkumar

#6921

Pl. check the @Rule and @RuleChain Migrations as I am  not sure if that is perfect, I avoided ExtendsWith as it was not so independent work

Also, make common jars come to junit4.gradle to make changes min in the future for such upgrade.

Kindly give your feedback, so that I can destroy my fork once this request is accepted and merged.

2023-05-12 18:16 UTC, eddumelendez requested changes
Thanks for your contribution and patience. I have left some comments.

2023-05-12 18:16 UTC, eddumelendez commented on examples/build.gradle
> +    apply plugin: "java"
let's avoid those kind of changes, please.

2023-05-12 18:16 UTC, eddumelendez commented on examples/build.gradle
> +    task prepareKotlinBuildScriptModel {
is this really needed?

2023-05-12 18:16 UTC, eddumelendez commented on examples/cucumber/build.gradle
> +    testImplementation 'io.cucumber:cucumber-junit:7.12.0'
if the bom is imported we can remove the version
```suggestion
    testImplementation 'io.cucumber:cucumber-junit'
```

2023-05-12 18:16 UTC, eddumelendez commented on examples/docs/ref/output.txt
> +C:\temp\ramu\testcontainers-java\examples>gradle clean test
remove this file

2023-05-12 18:16 UTC, eddumelendez commented on examples/hazelcast/build.gradle
> -    testImplementation 'org.assertj:assertj-core:3.24.2'
Let's avoid this. examples should contain everything is needed to run it.

2023-05-12 18:16 UTC, eddumelendez commented on examples/junit5.gradle
> +def jjVersion = "5.9.2"
remove this file, please. every project should be as clear as possible.

2023-05-13 10:40 UTC, closed without merging

2023-05-13 11:46 UTC, nagkumar commented
Thank You for the review, I shall raise a new PR with all the fixes, just one clarification to remove junit5.gradle point

The elimination of junit5.gralde would lead to adding all of the junit dependencies in each of the build file, that way when we move from junit 5 to say junit 6 again all these have to be changed in all of the examples, i.e. currently 17 examples exist, all the Gradle files have to change again to upgrade junit version.. 

If you are u ok with such repeat and error-prone (as they are so independent, some examples may still be using junit 5 and junit 6 etc..actually it **is already happening now while all the examples are junit 4, while neo4j-container is already junit 5** )

```
    testImplementation(platform("org.junit:junit-bom:$jjVersion"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testImplementation("org.junit.platform:junit-platform-suite")

    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
    testRuntimeOnly('org.junit.vintage:junit-vintage-engine')
```

<img width="470" alt="image" src="https://github.com/testcontainers/testcontainers-java/assets/332234/9f49fa72-f889-41a5-a1dd-53ef4767089a">

Please advise on this one point alone to share my revised PR.

2023-05-13 15:53 UTC, eddumelendez commented
new PR is not needed. Just update the branch used for this PR

2023-05-13 21:37 UTC, nagkumar commented
Just saw your message.. after I created a new PR.. hope you don't mind.. in all new code is the same repo.. but did do a fresh changes now.