Uses `clickhouse/clickhouse-server` as Docker Image in ClickHouseProvider
testcontainers/testcontainers-java pull request #8738
Opened 2024-05-31 05:23 UTC by linghengqian

- Fixes #8736 .
- Uses `clickhouse/clickhouse-server` as Docker Image in ClickHouseProvider.

2025-02-26 15:34 UTC, eddumelendez requested changes

2025-02-26 15:34 UTC, eddumelendez commented on modules/clickhouse/src/test/java/org/testcontainers/ClickhouseTestImages.java
> +    DockerImageName CLICKHOUSE_IMAGE = DockerImageName.parse("clickhouse/clickhouse-server:24.8.12.28");
I think it is worth to test against 21.9.2-alpine. That way any related change in the future will allow us to detect a regression.

2025-02-26 15:34 UTC, eddumelendez commented on modules/clickhouse/src/main/java/org/testcontainers/clickhouse/ClickHouseContainer.java
> +    public static final String CLICKHOUSE_CLICKHOUSE_SERVER = "clickhouse/clickhouse-server";
no public.

2025-02-27 15:55 UTC, linghengqian commented on modules/clickhouse/src/test/java/org/testcontainers/ClickhouseTestImages.java
> +    DockerImageName CLICKHOUSE_IMAGE = DockerImageName.parse("clickhouse/clickhouse-server:24.8.12.28");
Looks like `org.testcontainers.ClickhouseTestImages` has changed. Opening a PR has never been easier.

2025-02-27 15:55 UTC, linghengqian commented on modules/clickhouse/src/main/java/org/testcontainers/clickhouse/ClickHouseContainer.java
> +    public static final String CLICKHOUSE_CLICKHOUSE_SERVER = "clickhouse/clickhouse-server";
- Done.

2025-03-04 20:30 UTC, merged

2025-03-04 20:30 UTC, eddumelendez commented
Thanks for your contribution, @linghengqian !