Added example of how to run Hugging Face models through Ollama using TC
testcontainers/testcontainers-java pull request #8771
Opened 2024-06-11 15:06 UTC by ilopezluna

Added example of how to use `OllamaContainer` to run Hugging Face models

2024-06-12 09:29 UTC, kiview requested changes
For adding reuse support, see suggestions (try if they compile like this 😅 ).

2024-06-12 09:29 UTC, kiview commented on examples/ollama-hugging-face/src/test/java/com/example/ollamahf/OllamaHuggingFaceContainer.java
> +    protected void containerIsStarted(InspectContainerResponse containerInfo) {
```suggestion
    protected void containerIsStarted(InspectContainerResponse containerInfo, boolean reused) {
```

Support re-use.

2024-06-12 09:29 UTC, kiview commented on examples/ollama-hugging-face/src/test/java/com/example/ollamahf/OllamaHuggingFaceContainer.java
> +        super.containerIsStarted(containerInfo);
```suggestion
        super.containerIsStarted(containerInfo, reused);
         if (reused) {
           return;
         }
```

Don't download the model on re-use.

2024-06-27 16:07 UTC, eddumelendez requested changes
Thanks @ilopezluna! Left some comments to improve the example.

2024-06-27 16:07 UTC, eddumelendez commented on examples/ollama-hugging-face/src/test/java/com/example/ollamahf/OllamaHuggingFaceContainer.java
> +        }
I think we can move those commands to `containerIsStarted` and use `execInContainer` directly.

2024-06-27 16:07 UTC, eddumelendez commented on examples/ollama-hugging-face/src/test/java/com/example/ollamahf/OllamaHuggingFaceTest.java
> +            }
let's use the docker client API to check if the image exists, the code will be more readable.

2024-06-30 03:06 UTC, eddumelendez approved these changes

2024-06-30 03:07 UTC, merged

2024-06-30 03:07 UTC, eddumelendez commented
Thanks @ilopezluna !