Add Azure Eventhubs Emulator container to Azure module
testcontainers/testcontainers-java pull request #9665
Opened 2024-12-23 13:33 UTC by nagyesta

- Add Azure Eventhubs Emulator container
- Implement new test case
- Update Azure documentation

Must be merged after: #9661
Relates to: https://github.com/testcontainers/testcontainers-java/discussions/9607#discussioncomment-11525985

2025-01-09 22:16 UTC, eddumelendez requested changes

2025-01-09 22:16 UTC, eddumelendez commented on modules/azure/src/main/java/org/testcontainers/azure/AzureEventhubsEmulatorContainer.java
> +    }
Do not override `start()`. You can declare Azurite on `dependsOn` in the constructor. However, my concern would be the Azurite fixed version 🤔

2025-01-09 22:16 UTC, eddumelendez commented on modules/azure/src/main/java/org/testcontainers/azure/AzureEventhubsEmulatorContainer.java
> +    public AzureEventhubsEmulatorContainer withConfig(final MountableFile config) {
```suggestion
    public AzureEventhubsEmulatorContainer withConfig(final Transferable config) {
```

2025-01-09 22:16 UTC, eddumelendez commented on modules/azure/src/main/java/org/testcontainers/azure/AzureEventhubsEmulatorContainer.java
> +        return withEnv("ACCEPT_EULA", "Y");
follow [this pattern](https://github.com/testcontainers/testcontainers-java/blob/daf44c454ef6b0507b2138c1bbfcab83cb35c11e/modules/mssqlserver/src/main/java/org/testcontainers/containers/MSSQLServerContainer.java#L76-L79) to check if license was accepted

2025-01-09 22:16 UTC, eddumelendez commented on modules/azure/src/main/java/org/testcontainers/azure/AzureEventhubsEmulatorContainer.java
> +    private static final int DEFAULT_KAFKA_PORT = 9092;
kafka port is not used. Can we add a test? Otherwise, let's remove it.

2025-01-09 22:16 UTC, eddumelendez commented on modules/azure/src/test/java/org/testcontainers/azure/AzureEventhubsEmulatorContainerTest.java
> +    }
I don't think those are needed.

```suggestion
```

2025-01-09 22:44 UTC, nagyesta commented on modules/azure/src/main/java/org/testcontainers/azure/AzureEventhubsEmulatorContainer.java
> +    }
Thanks for the remarks! I have a couple of questions:
1. I wanted to make sure the containers are on the same network, but in the constructor it is too early to copy. Should I skip setting the network or add the dependency maybe in `cofigure()` rather?
2. The Azurite version is an interesting puzzle because we need another parameter if we want to ensure that people can override it. Would you be fine if I added another `DockerImageName` parameter to let the user define which Azurite image they want to use? I guess that is the cleanest because they can use custom repos or compatible images etc.

2025-01-09 22:50 UTC, nagyesta commented on modules/azure/src/main/java/org/testcontainers/azure/AzureEventhubsEmulatorContainer.java
> +    public AzureEventhubsEmulatorContainer withConfig(final MountableFile config) {
Should I update the Azurite config too similarly? It feels wrong to use two different approaches...

2025-01-09 22:55 UTC, nagyesta commented on modules/azure/src/main/java/org/testcontainers/azure/AzureEventhubsEmulatorContainer.java
> +    private static final int DEFAULT_KAFKA_PORT = 9092;
Thanks! Sure, I will add a test tomorrow.

2025-01-09 22:59 UTC, nagyesta commented on modules/azure/src/main/java/org/testcontainers/azure/AzureEventhubsEmulatorContainer.java
> +    }
Just realized, that configure is too late because the dependencies are started before.

2025-01-10 00:30 UTC, eddumelendez commented on modules/azure/src/main/java/org/testcontainers/azure/AzureEventhubsEmulatorContainer.java
> +    public AzureEventhubsEmulatorContainer withConfig(final MountableFile config) {
Using transferable for the config file makes sense because the json file can be built programmatically. I do not expect the same for the certificates. WDYT?

2025-01-10 00:31 UTC, eddumelendez commented on modules/azure/src/main/java/org/testcontainers/azure/AzureEventhubsEmulatorContainer.java
> +    }
I think, in the meantime, we can advocate to let the user declare the network and AzuriteContainer. This is one of the topic that depends on design.

2025-01-10 06:04 UTC, nagyesta commented on modules/azure/src/main/java/org/testcontainers/azure/AzureEventhubsEmulatorContainer.java
> +    public AzureEventhubsEmulatorContainer withConfig(final MountableFile config) {
To be honest I don't see the big difference but this might be just because I am not that familiar with these two types and the exact intent behind them (hopefully I will learn now). 
We can generate (or download from a secure place) a Java `KeyStore` without ever writing it to file, also if you want to generate a configuration json, it is a small step to write it to a temp file and then simply create a `MountableFile` with it. Or is the difference more nuanced?

2025-01-15 06:49 UTC, nagyesta commented on modules/azure/src/main/java/org/testcontainers/azure/AzureEventHubsEmulatorContainer.java
> +    public AzureEventHubsEmulatorContainer withConfig(final Transferable config) {
This could be copying the configuration right away.
```suggestion
    public AzureEventHubsEmulatorContainer withConfig(final Transferable config) {
        withCopyToContainer(this.config, "/Eventhubs_Emulator/ConfigFiles/Config.json");
```

2025-01-15 06:50 UTC, nagyesta commented on modules/azure/src/main/java/org/testcontainers/azure/AzureEventHubsEmulatorContainer.java
> +        }
No longer needed if the config is copied in the withConfig method
```suggestion
```

2025-01-16 22:02 UTC, nagyesta commented on modules/azure/src/main/java/org/testcontainers/azure/AzureEventHubsEmulatorContainer.java
> +    public AzureEventHubsEmulatorContainer(
I assume same as here: https://github.com/testcontainers/testcontainers-java/pull/9795#discussion_r1919118668

2025-01-23 18:03 UTC, nagyesta commented
Hi @eddumelendez ,
just a friendly reminder about this PR. Could you please take a look and respond to the still open threads?
Thank you in advance!

2025-01-24 16:15 UTC, eddumelendez commented on modules/azure/src/main/java/org/testcontainers/azure/AzureEventhubsEmulatorContainer.java
> +    public AzureEventhubsEmulatorContainer withConfig(final MountableFile config) {
`MountableFile` allows to copy files from host. Meanwhile `Transferable`, the interface it allows to pass a string that can be generated programmatically. Besides, it also accepts `MountableFile` because it implements `Transferable`.

Using `Transferable`, the API would be flexible enough for the user to choose.

2025-01-24 16:22 UTC, eddumelendez commented on modules/azure/src/main/java/org/testcontainers/azure/AzureEventHubsEmulatorContainer.java
> +public class AzureEventHubsEmulatorContainer extends GenericContainer<AzureEventHubsEmulatorContainer> {
We are not using the word Emulator on Azure module so let's be consistent.

```suggestion
public class AzureEventHubsContainer extends GenericContainer<AzureEventHubsEmulatorContainer> {
```

2025-01-24 16:22 UTC, eddumelendez commented on modules/azure/src/main/java/org/testcontainers/azure/AzureEventHubsEmulatorContainer.java
> +            this.addFixedExposedPort(DEFAULT_KAFKA_PORT, DEFAULT_KAFKA_PORT);
We must avoid fixed ports. `ConfluentKafkaContainer` and `KafkaContainer` configure the advertised listeners in order to accept connections from host. We should do something similar here if possible. Otherwise, let's remove it for now.

2025-01-24 18:20 UTC, nagyesta commented on modules/azure/src/main/java/org/testcontainers/azure/AzureEventhubsEmulatorContainer.java
> +    public AzureEventhubsEmulatorContainer withConfig(final MountableFile config) {
Okay, thank you for the explanation!

2025-01-24 20:43 UTC, nagyesta commented on modules/azure/src/main/java/org/testcontainers/azure/AzureEventHubsEmulatorContainer.java
> +public class AzureEventHubsEmulatorContainer extends GenericContainer<AzureEventHubsEmulatorContainer> {
Renamed. I assume you meant Azurite only because you are using the Emulator word in case of CosmosDB.

2025-01-24 20:44 UTC, nagyesta commented on modules/azure/src/main/java/org/testcontainers/azure/AzureEventHubsEmulatorContainer.java
> +            this.addFixedExposedPort(DEFAULT_KAFKA_PORT, DEFAULT_KAFKA_PORT);
Okay, removed Kafka from this container. Most probably anyone using Kafka would use a real Kafka container locally anyways.

2025-01-27 17:00 UTC, merged

2025-01-27 17:00 UTC, eddumelendez commented
Thanks for your contribution, @nagyesta !

2025-01-27 20:17 UTC, nagyesta commented
Thank you for the review!